In [1]:
import pandas as pd
import numpy as np

### Построение модели

In [2]:
df = pd.read_csv(r'telco-customer-churn.csv', sep = ',')

In [3]:
pd.set_option('display.max_columns', 200)
pd.set_option('max_rows', 500)
pd.options.mode.chained_assignment = None

In [4]:
df.isnull().sum()
# Данные довольно качественные, пропуски отсутствуют во всех столбцах

age                                     0
annualincome                            0
calldroprate                            0
callfailurerate                         0
callingnum                              0
customerid                              0
customersuspended                       0
education                               0
gender                                  0
homeowner                               0
maritalstatus                           0
monthlybilledamount                     0
noadditionallines                       0
numberofcomplaints                      0
numberofmonthunpaid                     0
numdayscontractequipmentplanexpiring    0
occupation                              0
penaltytoswitch                         0
state                                   0
totalminsusedinlastmonth                0
unpaidbalance                           0
usesinternetservice                     0
usesvoiceservice                        0
percentagecalloutsidenetwork            0
totalcallduration                       0
avgcallduration                         0
churn                                   0
year                                    0
month                                   0
dtype: int64

##### Опишем существующие признаки:

age      -      возраст;                                    
annualincome    -   входящие за год (скорее всего секунды);                       
calldroprate   -   частота пропущенных вызовов;                    
callfailurerate  - частота недозвонов;               
callingnum   -  номер телефона;                              
customerid   - id клиента;               
customersuspended        -    подвешенный клиент;             
education      -   образование клиента;
gender      -   пол клиента;                               
homeowner        -       дом принадлежит абоненту;                
maritalstatus       -   женат/не женат;             
monthlybilledamount         -    месячная плата по счету;            
noadditionallines      -      доп.услуги (линии);
numberofcomplaints        -    количество жалоб;              
numberofmonthunpaid         -      количество неоплаченных месяцев;    
numdayscontractequipmentplanexpiring       -    дни аренды оборудования;
occupation      -    род занятий;                        
penaltytoswitch            -    штраф до отключения;             
state          -      Штат (регион);           
totalminsusedinlastmonth          -    количество чего-то за последний месяц;      
unpaidbalance           -      величина неоплаченного баланса;
usesinternetservice      -             интернет-сервис (да-нет);    
usesvoiceservice         -             голосовой сервис (да-нет);           
percentagecalloutsidenetwork        -      звонки вне сети;
totalcallduration          -         общая длительность звонков;   
avgcallduration         -      средняя продолжительность звонков;                 
churn                  -    отток (целевая переменная);
year          -    год;                         
month          -      месяц - 1,2,3;

In [5]:
corr_matrix = df.corr()

In [6]:
import seaborn as sns
sns.heatmap(corr_matrix);
# сильно коррелирующих предикторов нет

In [7]:
df[df.duplicated()]
# Дублей также нет в датасете

Empty DataFrame
Columns: [age, annualincome, calldroprate, callfailurerate, callingnum, customerid, customersuspended, education, gender, homeowner, maritalstatus, monthlybilledamount, noadditionallines, numberofcomplaints, numberofmonthunpaid, numdayscontractequipmentplanexpiring, occupation, penaltytoswitch, state, totalminsusedinlastmonth, unpaidbalance, usesinternetservice, usesvoiceservice, percentagecalloutsidenetwork, totalcallduration, avgcallduration, churn, year, month]
Index: []

In [8]:
df

,age,annualincome,calldroprate,callfailurerate,callingnum,customerid,customersuspended,education,gender,homeowner,maritalstatus,monthlybilledamount,noadditionallines,numberofcomplaints,numberofmonthunpaid,numdayscontractequipmentplanexpiring,occupation,penaltytoswitch,state,totalminsusedinlastmonth,unpaidbalance,usesinternetservice,usesvoiceservice,percentagecalloutsidenetwork,totalcallduration,avgcallduration,churn,year,month
0,12,168147,0.06,0.00,4251078442,1,Yes,Bachelor or equivalent,Male,Yes,Single,71,\N,0,7,96,Technology Related Job,371,WA,15,19,No,No,0.82,5971,663,0,2015,1
1,12,168147,0.06,0.00,4251078442,1,Yes,Bachelor or equivalent,Male,Yes,Single,71,\N,0,7,96,Technology Related Job,371,WA,15,19,No,No,0.82,3981,995,0,2015,2
2,42,29047,0.05,0.01,4251043419,2,Yes,Bachelor or equivalent,Female,Yes,Single,8,\N,1,4,14,Technology Related Job,43,WI,212,34,No,Yes,0.27,7379,737,0,2015,1
3,42,29047,0.05,0.01,4251043419,2,Yes,Bachelor or equivalent,Female,Yes,Single,8,\N,1,4,14,Technology Related Job,43,WI,212,34,No,Yes,0.27,1729,432,0,2015,2
4,58,27076,0.07,0.02,4251055773,3,Yes,Master or equivalent,Female,Yes,Single,16,\N,0,2,55,Technology Related Job,403,KS,216,144,No,No,0.48,3122,624,0,2015,1
5,58,27076,0.07,0.02,4251055773,3,Yes,Master or equivalent,Female,Yes,Single,16,\N,0,2,55,Technology Related Job,403,KS,216,144,No,No,0.48,2769,553,0,2015,2
6,20,137977,0.05,0.03,4251042488,4,Yes,PhD or equivalent,Male,No,Single,74,\N,1,7,73,Technology Related Job,76,KY,412,159,Yes,No,0.94,834,834,0,2015,1
7,20,137977,0.05,0.03,4251042488,4,Yes,PhD or equivalent,Male,No,Single,74,\N,1,7,73,Technology Related Job,76,KY,412,159,Yes,No,0.94,5868,838,0,2015,2
8,36,136006,0.07,0.00,4251073177,5,Yes,High School or below,Male,Yes,Married,81,\N,0,5,14,Technology Related Job,436,ND,416,19,No,No,0.15,1886,628,0,2015,1
9,36,136006,0.07,0.00,4251073177,5,Yes,High School or below,Male,Yes,Married,81,\N,0,5,14,Technology Related Job,436,ND,416,19,No,No,0.15,2602,867,0,2015,2
10,67,246906,0.05,0.01,4251023523,6,Yes,High School or below,Female,Yes,Married,19,\N,1,2,32,Technology Related Job,108,OK,113,34,No,No,0.61,2737,391,0,2015,1
11,67,246906,0.05,0.01,4251023523,6,Yes,High School or below,Female,Yes,Married,19,\N,1,2,32,Technology Related Job,108,OK,113,34,No,No,0.61,5845,835,0,2015,2
12,14,244935,0.07,0.02,4251055777,7,Yes,High School or below,Male,Yes,Single,27,\N,3,0,73,Technology Related Job,468,AZ,116,144,No,No,0.82,3342,557,0,2015,1
13,14,244935,0.07,0.02,4251055777,7,Yes,High School or below,Male,Yes,Single,27,\N,3,0,73,Technology Related Job,468,AZ,116,144,No,No,0.82,2428,809,0,2015,2
14,45,105835,0.05,0.03,4251045184,8,Yes,High School or below,Female,Yes,Married,85,\N,1,5,91,Technology Related Job,141,CA,313,159,No,No,0.27,2446,815,0,2015,1
15,45,105835,0.05,0.03,4251045184,8,Yes,High School or below,Female,Yes,Married,85,\N,1,5,91,Technology Related Job,141,CA,313,159,No,No,0.27,4882,813,0,2015,2
16,61,103864,0.07,0.00,4251031912,9,Yes,Bachelor or equivalent,Female,Yes,Single,92,\N,3,3,32,Technology Related Job,1,MI,316,19,No,No,0.48,2065,516,0,2015,1
17,61,103864,0.07,0.00,4251031912,9,Yes,Bachelor or equivalent,Female,Yes,Single,92,\N,3,3,32,Technology Related Job,1,MI,316,19,No,No,0.48,2802,560,0,2015,2
18,61,103864,0.07,0.00,4251031912,9,Yes,Bachelor or equivalent,Female,Yes,Single,92,\N,3,3,32,Technology Related Job,1,MI,316,19,No,No,0.48,268,268,0,2015,3
19,23,214765,0.06,0.01,4251042084,10,Yes,Bachelor or equivalent,Male,Yes,Single,30,\N,0,0,50,Technology Related Job,173,MN,13,34,No,No,0.94,3022,755,1,2015,1
20,23,214765,0.06,0.01,4251042084,10,Yes,Bachelor or equivalent,Male,Yes,Single,30,\N,0,0,50,Technology Related Job,173,MN,13,34,No,No,0.94,3076,615,1,2015,2
21,23,214765,0.06,0.01,4251042084,10,Yes,Bachelor or equivalent,Male,Yes,Single,30,\N,0,0,50,Technology Related Job,173,MN,13,34,No,No,0.94,626,626,1,2015,3
22,39,212794,0.00,0.02,4251079715,11,Yes,Master or equivalent,Female,Yes,Married,37,\N,3,6,91,Technology Related Job,34,SC,17,144,No,Yes,0.15,3968,661,0,2015,1
23,39,212794,0.00,0.02,4251079715,11,Yes,Master or equivalent,Female,Yes,Married,37,\N,3,6,91,Technology Related Job,34,SC,17,144,No,Yes,0.15,3685,737,0,2015,2
24,69,73694,0.06,0.03,4251022028,12,Yes,Master or equivalent,Male,No,Married,95,\N,0,4,9,Technology Related Job,206,TN,214,159,No,No,0.61,1392,696,0,2015,1
25,69,73694,0.06,0.03,4251022028,12,Yes,Master or equivalent,Male,No,Married,95,\N,0,4,9,Technology Related Job,206,TN,214,159,No,No,0.61,1456,485,0,2015,2
26,69,73694,0.06,0.03,4251022028,12,Yes,Master or equivalent,Male,No,Married,95,\N,0,4,9,Technology Related Job,206,TN,214,159,No,No,0.61,378,378,0,2015,3
27,17,71723,0.00,0.00,4251047310,13,Yes,High School or below,Male,No,Married,103,\N,3,1,50,Technology Related Job,66,FL,217,19,No,No,0.82,6780,968,0,2015,1
28,17,71723,0.00,0.00,4251047310,13,Yes,High School or below,Male,No,Married,103,\N,3,1,50,Technology Related Job,66,FL,217,19,No,No,0.82,2277,1138,0,2015,2
29,48,182623,0.06,0.01,4251072591,14,Yes,High School or below,Female,Yes,Married,41,\N,0,7,68,Technology Related Job,239,HI,414,34,No,No,0.27,3877,775,0,2015,1
30,48,182623,0.06,0.01,4251072591,14,Yes,High School or below,Female,Yes,Married,41,\N,0,7,68,Technology Related Job,239,HI,414,34,No,No,0.27,2675,1337,0,2015,2
31,64,180652,0.00,0.02,4251060013,15,Yes,High School or below,Female,Yes,Single,48,\N,2,4,8,Technology Related Job,99,NV,417,144,No,No,0.48,3624,604,0,2015,1
32,64,180652,0.00,0.02,4251060013,15,Yes,High School or below,Female,Yes,Single,48,\N,2,4,8,Technology Related Job,99,NV,417,144,No,No,0.48,825,412,0,2015,2
33,26,41553,0.06,0.03,4251042322,16,Yes,High School or below,Male,Yes,Single,106,\N,0,2,27,Technology Related Job,271,NH,114,159,No,No,0.94,3595,599,0,2015,1
34,26,41553,0.06,0.03,4251042322,16,Yes,High School or below,Male,Yes,Single,106,\N,0,2,27,Technology Related Job,271,NH,114,159,No,No,0.94,1890,472,0,2015,2
35,26,41553,0.06,0.03,4251042322,16,Yes,High School or below,Male,Yes,Single,106,\N,0,2,27,Technology Related Job,271,NH,114,159,No,No,0.94,1248,1248,0,2015,3
36,42,39582,0.00,0.00,4251011152,17,Yes,Bachelor or equivalent,Female,Yes,Married,114,\N,2,7,67,Technology Related Job,131,VA,118,19,No,No,0.15,3716,929,0,2015,1
37,42,39582,0.00,0.00,4251011152,17,Yes,Bachelor or equivalent,Female,Yes,Married,114,\N,2,7,67,Technology Related Job,131,VA,118,19,No,No,0.15,3966,661,0,2015,2
38,72,150482,0.07,0.01,4251051704,18,Yes,Bachelor or equivalent,Male,No,Single,52,\N,3,5,86,Non-technology Related Job,304,WV,315,34,No,No,0.61,3646,607,0,2015,1
39,72,150482,0.07,0.01,4251051704,18,Yes,Bachelor or equivalent,Male,No,Single,52,\N,3,5,86,Non-technology Related Job,304,WV,315,34,No,No,0.61,4605,767,0,2015,2
40,20,148511,0.01,0.02,4251070591,19,Yes,Master or equivalent,Male,Yes,Married,59,\N,2,2,26,Technology Related Job,164,IA,318,144,No,No,0.82,6031,861,0,2015,1
41,20,148511,0.01,0.02,4251070591,19,Yes,Master or equivalent,Male,Yes,Married,59,\N,2,2,26,Technology Related Job,164,IA,318,144,No,No,0.82,3828,765,0,2015,2
42,50,9412,0.07,0.03,4251047771,20,Yes,Master or equivalent,Female,Yes,Married,117,\N,3,0,45,Non-technology Related Job,336,KY,15,159,No,No,0.28,1922,961,0,2015,1
43,50,9412,0.07,0.03,4251047771,20,Yes,Master or equivalent,Female,Yes,Married,117,\N,3,0,45,Non-technology Related Job,336,KY,15,159,No,No,0.28,2659,886,0,2015,2
44,66,7441,0.01,0.00,4251079003,21,Yes,High School or below,Female,Yes,Single,4,\N,1,5,85,Technology Related Job,196,ND,18,19,No,No,0.49,4680,936,0,2015,1
45,66,7441,0.01,0.00,4251079003,21,Yes,High School or below,Female,Yes,Single,4,\N,1,5,85,Technology Related Job,196,ND,18,19,No,No,0.49,2918,729,0,2015,2
46,29,118341,0.07,0.01,4251043431,22,Yes,High School or below,Male,Yes,Single,62,\N,3,3,4,Non-technology Related Job,369,OH,215,34,No,No,0.94,4746,527,0,2015,1
47,29,118341,0.07,0.01,4251043431,22,Yes,High School or below,Male,Yes,Single,62,\N,3,3,4,Non-technology Related Job,369,OH,215,34,No,No,0.94,5287,881,0,2015,2
48,29,118341,0.07,0.01,4251043431,22,Yes,High School or below,Male,Yes,Single,62,\N,3,3,4,Non-technology Related Job,369,OH,215,34,No,No,0.94,995,497,0,2015,3
49,45,116370,0.01,0.02,4251010033,23,Yes,High School or below,Female,Yes,Single,70,\N,1,0,44,Technology Related Job,229,AK,219,144,No,No,0.15,1175,587,0,2015,1
50,45,116370,0.01,0.02,4251010033,23,Yes,High School or below,Female,Yes,Single,70,\N,1,0,44,Technology Related Job,229,AK,219,144,No,No,0.15,5389,598,0,2015,2
51,75,227270,0.07,0.03,4251016886,24,Yes,High School or below,Male,Yes,Single,8,\N,2,6,63,Non-technology Related Job,401,AR,416,159,No,Yes,0.61,4992,998,0,2015,1
52,75,227270,0.07,0.03,4251016886,24,Yes,High School or below,Male,Yes,Single,8,\N,2,6,63,Non-technology Related Job,401,AR,416,159,No,Yes,0.61,4041,505,0,2015,2
53,23,225299,0.01,0.00,4251045842,25,Yes,Bachelor or equivalent,Male,Yes,Married,15,\N,1,3,3,Technology Related Job,261,MA,419,19,No,No,0.82,3219,643,0,2015,1
54,23,225299,0.01,0.00,4251045842,25,Yes,Bachelor or equivalent,Male,Yes,Married,15,\N,1,3,3,Technology Related Job,261,MA,419,19,No,No,0.82,3228,645,0,2015,2
55,53,86200,0.00,0.00,4251043061,26,Yes,Bachelor or equivalent,Female,Yes,Married,73,\N,2,1,22,Non-technology Related Job,434,MN,116,34,No,No,0.28,5926,592,0,2015,1
56,53,86200,0.00,0.00,4251043061,26,Yes,Bachelor or equivalent,Female,Yes,Married,73,\N,2,1,22,Non-technology Related Job,434,MN,116,34,No,No,0.28,1875,625,0,2015,2
57,69,84229,0.02,0.02,4251098247,27,Yes,Bachelor or equivalent,Female,No,Single,81,\N,1,6,62,Technology Related Job,294,SC,119,144,No,No,0.49,7748,704,0,2015,1
58,69,84229,0.02,0.02,4251098247,27,Yes,Bachelor or equivalent,Female,No,Single,81,\N,1,6,62,Technology Related Job,294,SC,119,144,No,No,0.49,6669,833,0,2015,2
59,69,84229,0.02,0.02,4251098247,27,Yes,Bachelor or equivalent,Female,No,Single,81,\N,1,6,62,Technology Related Job,294,SC,119,144,No,No,0.49,405,405,0,2015,3
60,31,195129,0.00,0.02,4251026170,28,Yes,Master or equivalent,Male,Yes,Married,18,\N,2,4,81,Non-technology Related Job,466,SD,316,159,No,No,0.94,7215,721,0,2015,1
61,31,195129,0.00,0.02,4251026170,28,Yes,Master or equivalent,Male,Yes,Married,18,\N,2,4,81,Non-technology Related Job,466,SD,316,159,No,No,0.94,1614,807,0,2015,2
62,47,193158,0.02,0.00,4251011887,29,Yes,High School or below,Female,Yes,Single,26,\N,0,1,21,Technology Related Job,327,DE,320,19,Yes,No,0.15,6115,611,0,2015,1
63,47,193158,0.02,0.00,4251011887,29,Yes,High School or below,Female,Yes,Single,26,\N,0,1,21,Technology Related Job,327,DE,320,19,Yes,No,0.15,2102,420,0,2015,2
64,78,54058,0.00,0.00,4251017032,30,Yes,High School or below,Male,Yes,Single,84,\N,2,7,39,Non-technology Related Job,499,GA,16,34,No,No,0.61,4933,704,0,2015,1
65,78,54058,0.00,0.00,4251017032,30,Yes,High School or below,Male,Yes,Single,84,\N,2,7,39,Non-technology Related Job,499,GA,16,34,No,No,0.61,6507,813,0,2015,2
66,26,52087,0.02,0.02,4251029808,31,Yes,High School or below,Male,Yes,Married,91,\N,0,5,80,Technology Related Job,359,NE,20,144,No,No,0.82,2707,541,0,2015,1
67,26,52087,0.02,0.02,4251029808,31,Yes,High School or below,Male,Yes,Married,91,\N,0,5,80,Technology Related Job,359,NE,20,144,No,No,0.82,5199,742,0,2015,2
68,26,52087,0.02,0.02,4251029808,31,Yes,High School or below,Male,Yes,Married,91,\N,0,5,80,Technology Related Job,359,NE,20,144,No,No,0.82,270,270,0,2015,3
69,56,162988,0.00,0.02,4251040357,32,Yes,High School or below,Female,No,Married,29,\N,1,2,98,Non-technology Related Job,32,NH,217,159,No,No,0.28,3978,795,0,2015,1
70,56,162988,0.00,0.02,4251040357,32,Yes,High School or below,Female,No,Married,29,\N,1,2,98,Non-technology Related Job,32,NH,217,159,No,No,0.28,3795,759,0,2015,2
71,72,161017,0.02,0.00,4251093174,33,Yes,High School or below,Female,Yes,Married,37,\N,0,0,39,Technology Related Job,392,VA,220,19,No,Yes,0.49,1596,399,0,2015,1
72,72,161017,0.02,0.00,4251093174,33,Yes,High School or below,Female,Yes,Married,37,\N,0,0,39,Technology Related Job,392,VA,220,19,No,Yes,0.49,7474,1067,0,2015,2
73,34,21917,0.01,0.00,4251076747,34,Yes,Bachelor or equivalent,Male,Yes,Married,95,\N,1,5,57,Non-technology Related Job,64,WA,417,34,No,No,0.94,5974,746,0,2015,1
74,34,21917,0.01,0.00,4251076747,34,Yes,Bachelor or equivalent,Male,Yes,Married,95,\N,1,5,57,Non-technology Related Job,64,WA,417,34,No,No,0.94,3903,975,0,2015,2
75,34,21917,0.01,0.00,4251076747,34,Yes,Bachelor or equivalent,Male,Yes,Married,95,\N,1,5,57,Non-technology Related Job,64,WA,417,34,No,No,0.94,331,331,0,2015,3
76,50,19946,0.03,0.02,4251068765,35,Yes,Bachelor or equivalent,Female,Yes,Single,102,\N,0,3,98,Technology Related Job,424,IN,420,144,No,No,0.16,2198,732,0,2015,1
77,50,19946,0.03,0.02,4251068765,35,Yes,Bachelor or equivalent,Female,Yes,Single,102,\N,0,3,98,Technology Related Job,424,IN,420,144,No,No,0.16,8067,733,0,2015,2
78,13,130846,0.01,0.02,4251081945,36,Yes,Bachelor or equivalent,Male,Yes,Single,40,\N,1,0,16,Non-technology Related Job,97,KS,117,159,No,No,0.61,3994,998,0,2015,1
79,13,130846,0.01,0.02,4251081945,36,Yes,Bachelor or equivalent,Male,Yes,Single,40,\N,1,0,16,Non-technology Related Job,97,KS,117,159,No,No,0.61,4002,1000,0,2015,2
80,13,130846,0.01,0.02,4251081945,36,Yes,Bachelor or equivalent,Male,Yes,Single,40,\N,1,0,16,Non-technology Related Job,97,KS,117,159,No,No,0.61,1083,1083,0,2015,3
81,28,128875,0.03,0.00,4251070137,37,Yes,PhD or equivalent,Male,Yes,Married,47,\N,3,6,57,Technology Related Job,457,NC,121,19,No,No,0.82,1384,346,0,2015,1
82,28,128875,0.03,0.00,4251070137,37,Yes,PhD or equivalent,Male,Yes,Married,47,\N,3,6,57,Technology Related Job,457,NC,121,19,No,No,0.82,4753,950,0,2015,2
83,59,239776,0.01,0.00,4251075538,38,Yes,High School or below,Female,Yes,Single,105,\N,1,3,75,Non-technology Related Job,129,OH,318,34,No,No,0.28,2849,949,0,2015,1
84,59,239776,0.01,0.00,4251075538,38,Yes,High School or below,Female,Yes,Single,105,\N,1,3,75,Non-technology Related Job,129,OH,318,34,No,No,0.28,3537,707,0,2015,2
85,59,239776,0.01,0.00,4251075538,38,Yes,High School or below,Female,Yes,Single,105,\N,1,3,75,Non-technology Related Job,129,OH,318,34,No,No,0.28,2622,1311,0,2015,3
86,75,237805,0.03,0.02,4251098864,39,Yes,High School or below,Female,Yes,Married,113,\N,3,1,16,Technology Related Job,489,AK,321,143,No,No,0.49,3015,603,0,2015,1
87,75,237805,0.03,0.02,4251098864,39,Yes,High School or below,Female,Yes,Married,113,\N,3,1,16,Technology Related Job,489,AK,321,143,No,No,0.49,1514,504,0,2015,2
88,37,98705,0.01,0.02,4251076763,40,Yes,High School or below,Male,Yes,Married,51,\N,0,6,34,Non-technology Related Job,162,AR,18,158,No,No,0.95,5173,862,0,2015,1
89,37,98705,0.01,0.02,4251076763,40,Yes,High School or below,Male,Yes,Married,51,\N,0,6,34,Non-technology Related Job,162,AR,18,158,No,No,0.95,2143,428,0,2015,2
90,53,96734,0.03,0.00,4251067408,41,Yes,High School or below,Female,No,Single,58,\N,3,4,75,Technology Related Job,22,MD,21,18,No,No,0.16,2614,326,0,2015,1
91,53,96734,0.03,0.00,4251067408,41,Yes,High School or below,Female,No,Single,58,\N,3,4,75,Technology Related Job,22,MD,21,18,No,No,0.16,2175,1087,0,2015,2
92,15,207635,0.02,0.00,4251074247,42,Yes,Bachelor or equivalent,Male,Yes,Single,116,\N,0,2,93,Non-technology Related Job,194,MI,218,33,No,No,0.61,5422,1084,1,2015,1
93,15,207635,0.02,0.00,4251074247,42,Yes,Bachelor or equivalent,Male,Yes,Single,116,\N,0,2,93,Non-technology Related Job,194,MI,218,33,No,No,0.61,2938,734,1,2015,2
94,31,205664,0.04,0.02,4251021408,43,Yes,Bachelor or equivalent,Male,Yes,Single,4,\N,2,7,33,Technology Related Job,54,RI,222,143,No,No,0.82,2916,583,0,2015,1
95,31,205664,0.04,0.02,4251021408,43,Yes,Bachelor or equivalent,Male,Yes,Single,4,\N,2,7,33,Technology Related Job,54,RI,222,143,No,No,0.82,3946,657,0,2015,2
96,62,66564,0.02,0.02,4251086886,44,Yes,Bachelor or equivalent,Female,Yes,Single,62,\N,0,5,52,Non-technology Related Job,227,SD,419,158,No,No,0.28,7311,609,0,2015,1
97,62,66564,0.02,0.02,4251086886,44,Yes,Bachelor or equivalent,Female,Yes,Single,62,\N,0,5,52,Non-technology Related Job,227,SD,419,158,No,No,0.28,582,582,0,2015,2
98,62,66564,0.02,0.02,4251086886,44,Yes,Bachelor or equivalent,Female,Yes,Single,62,\N,0,5,52,Non-technology Related Job,227,SD,419,158,No,No,0.28,1340,1340,0,2015,3
99,77,64593,0.04,0.00,4251086023,45,Yes,Master or equivalent,Male,Yes,Married,69,\N,2,2,92,Technology Related Job,87,DE,422,18,No,No,0.49,1761,587,0,2015,1
100,77,64593,0.04,0.00,4251086023,45,Yes,Master or equivalent,Male,Yes,Married,69,\N,2,2,92,Technology Related Job,87,DE,422,18,No,No,0.49,7002,1000,0,2015,2
101,40,175493,0.02,0.00,4251012570,46,Yes,PhD or equivalent,Female,No,Married,7,\N,3,0,11,Non-technology Related Job,259,GA,119,33,No,Yes,0.95,5350,668,0,2015,1
102,40,175493,0.02,0.00,4251012570,46,Yes,PhD or equivalent,Female,No,Married,7,\N,3,0,11,Non-technology Related Job,259,GA,119,33,No,Yes,0.95,3806,761,0,2015,2
103,56,173522,0.04,0.02,4251066935,47,Yes,High School or below,Female,No,Single,14,\N,2,5,51,Technology Related Job,120,MT,122,143,No,No,0.16,3793,948,0,2015,1
104,56,173522,0.04,0.02,4251066935,47,Yes,High School or below,Female,No,Single,14,\N,2,5,51,Technology Related Job,120,MT,122,143,No,No,0.16,3670,734,0,2015,2
105,18,34423,0.02,0.02,4251098797,48,Yes,High School or below,Male,Yes,Single,72,\N,3,3,70,Non-technology Related Job,292,NV,319,158,No,No,0.61,7422,530,0,2015,1
106,18,34423,0.02,0.02,4251098797,48,Yes,High School or below,Male,Yes,Single,72,\N,3,3,70,Non-technology Related Job,292,NV,319,158,No,No,0.61,3907,976,0,2015,2
107,18,34423,0.02,0.02,4251098797,48,Yes,High School or below,Male,Yes,Single,72,\N,3,3,70,Non-technology Related Job,292,NV,319,158,No,No,0.61,867,867,0,2015,3
108,34,32452,0.04,0.00,4251056800,49,Yes,High School or below,Male,Yes,Single,80,\N,2,0,10,Technology Related Job,152,VT,323,18,No,No,0.83,6501,812,0,2015,1
109,34,32452,0.04,0.00,4251056800,49,Yes,High School or below,Male,Yes,Single,80,\N,2,0,10,Technology Related Job,152,VT,323,18,No,No,0.83,1937,484,0,2015,2
110,64,143352,0.03,0.00,4251010715,50,Yes,High School or below,Female,Yes,Single,18,\N,3,6,29,Non-technology Related Job,325,WA,20,33,No,No,0.28,2851,950,0,2015,1
111,64,143352,0.03,0.00,4251010715,50,Yes,High School or below,Female,Yes,Single,18,\N,3,6,29,Non-technology Related Job,325,WA,20,33,No,No,0.28,4723,674,0,2015,2
112,64,143352,0.03,0.00,4251010715,50,Yes,High School or below,Female,Yes,Single,18,\N,3,6,29,Non-technology Related Job,325,WA,20,33,No,No,0.28,862,862,0,2015,3
113,67,198309,0.06,0.00,4251036375,51,Yes,Bachelor or equivalent,Female,No,Married,109,\N,0,0,98,Non-technology Related Job,1,SC,119,68,No,No,0.81,4356,622,0,2015,1
114,67,198309,0.06,0.00,4251036375,51,Yes,Bachelor or equivalent,Female,No,Married,109,\N,0,0,98,Non-technology Related Job,1,SC,119,68,No,No,0.81,3844,427,0,2015,2
115,14,196338,0.00,0.02,4251094710,52,Yes,Bachelor or equivalent,Female,No,Single,116,\N,3,5,39,Technology Related Job,361,CO,122,178,No,No,0.02,1603,400,0,2015,1
116,14,196338,0.00,0.02,4251094710,52,Yes,Bachelor or equivalent,Female,No,Single,116,\N,3,5,39,Technology Related Job,361,CO,122,178,No,No,0.02,964,482,0,2015,2
117,45,57239,0.07,0.02,4251034334,53,Yes,Bachelor or equivalent,Male,Yes,Single,54,\N,0,3,57,Non-technology Related Job,33,DE,319,193,No,No,0.48,4873,812,0,2015,1
118,45,57239,0.07,0.02,4251034334,53,Yes,Bachelor or equivalent,Male,Yes,Single,54,\N,0,3,57,Non-technology Related Job,33,DE,319,193,No,No,0.48,4273,1068,0,2015,2
119,61,55268,0.01,0.03,4251094629,54,Yes,Master or equivalent,Female,Yes,Married,61,\N,2,1,97,Technology Related Job,393,MO,322,53,No,No,0.69,6260,894,0,2015,1
120,61,55268,0.01,0.03,4251094629,54,Yes,Master or equivalent,Female,Yes,Married,61,\N,2,1,97,Technology Related Job,393,MO,322,53,No,No,0.69,7081,885,0,2015,2
121,61,55268,0.01,0.03,4251094629,54,Yes,Master or equivalent,Female,Yes,Married,61,\N,2,1,97,Technology Related Job,393,MO,322,53,No,No,0.69,773,386,0,2015,3

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20468 entries, 0 to 20467
Data columns (total 29 columns):
age                                     20468 non-null int64
annualincome                            20468 non-null int64
calldroprate                            20468 non-null float64
callfailurerate                         20468 non-null float64
callingnum                              20468 non-null int64
customerid                              20468 non-null int64
customersuspended                       20468 non-null object
education                               20468 non-null object
gender                                  20468 non-null object
homeowner                               20468 non-null object
maritalstatus                           20468 non-null object
monthlybilledamount                     20468 non-null int64
noadditionallines                       20468 non-null object
numberofcomplaints                      20468 non-null int64
numberofmonthunpaid                     20468 non-null int64
numdayscontractequipmentplanexpiring    20468 non-null int64
occupation                              20468 non-null object
penaltytoswitch                         20468 non-null int64
state                                   20468 non-null object
totalminsusedinlastmonth                20468 non-null int64
unpaidbalance                           20468 non-null int64
usesinternetservice                     20468 non-null object
usesvoiceservice                        20468 non-null object
percentagecalloutsidenetwork            20468 non-null float64
totalcallduration                       20468 non-null int64
avgcallduration                         20468 non-null int64
churn                                   20468 non-null int64
year                                    20468 non-null int64
month                                   20468 non-null int64
dtypes: float64(3), int64(16), object(10)
memory usage: 4.5+ MB

In [10]:
# Посмотрим, какие значения принимают наши признаки
for i in df.columns:
    print(i, df[i].unique())

age [12 42 58 20 36 67 14 45 61 23 39 69 17 48 64 26 72 50 66 29 75 53 31 47
 78 56 34 13 28 59 37 15 62 77 40 18 43 21 24 70 27 73 51 76 54 32 57 35
 38 16 19 65 22 68 46 71 49 52 30 33 79 60 63 41 44 25 74 55]
annualincome [168147  29047  27076 ...  67056  65084 120042]
calldroprate [0.06 0.05 0.07 0.   0.01 0.02 0.03 0.04]
callfailurerate [0.   0.01 0.02 0.03]
callingnum [4251078442 4251043419 4251055773 ... 4251050233 4251050074 4251075688]
customerid [   1    2    3 ... 9523 9524 9525]
customersuspended ['Yes' 'No']
education ['Bachelor or equivalent' 'Master or equivalent' 'PhD or equivalent'
 'High School or below']
gender ['Male' 'Female']
homeowner ['Yes' 'No']
maritalstatus ['Single' 'Married']
monthlybilledamount [ 71   8  16  74  81  19  27  85  92  30  37  95 103  41  48 106 114  52
  59 117   4  62  70  15  73  18  26  84  91  29 102  40  47 105 113  51
  58 116  69   7  14  72  80 109  54  61 119  65  10  75  83  21  28  86
  94  32  39  97 104  42  50 108 115  53   6  64   9  17  82  20  93  31
  38  96  49 107  60 118   5  63  25  36 101 112   3  68  79  90  35  46
 111  57   2  13  78  24  89 100  45  56   1  67  12  23  88  34  99 110
  55  66  77  22  33  98  44   0  11  76  87  43]
noadditionallines ['\\N']
numberofcomplaints [0 1 3 2]
numberofmonthunpaid [7 4 2 5 0 3 6 1]
numdayscontractequipmentplanexpiring [96 14 55 73 32 91 50  9 68  8 27 67 86 26 45 85  4 44 63  3 22 62 81 21
 39 80 98 57 16 75 34 93 33 52 92 11 51 70 10 29 97 56 15 74 69 87 28 46
  5 64 23 82 41  0 40 59 99 18 58 77 17 36 76 95 35 54 94 12 53 71 30 89
 48  7 66  6 25 65 84 24 43 83  2 42 61  1 20 60 79 19 37 78 90 49 88 13
 72 38 47 31]
occupation ['Technology Related Job' 'Non-technology Related Job' 'Others']
penaltytoswitch [371  43 403  76 436 108 468 141   1 173  34 206  66 239  99 271 131 304
 164 336 196 369 229 401 261 434 294 466 327 499 359  32 392  64 424  97
 457 129 489 162  22 194  54 227  87 259 120 292 152 325 361  33 393 426
  98 459 491  24  56  89 121 154 326 186 219 391 252 284 317 349 382 414
 447 119 479  12 184  45 217  77 250 110 282 142 315 175 347 207 380 240
 412 272 445 305 477 338  10 370  75 435 140   0 205 238 270 303 163 368
 228 433 293 498  31  63  96 456 161  21 226  86 291 324 356 389 249 422
 454 314 487  19 379  52  84 117 149 182  42 215 247 107 280 312 172 345
 377 410 442 475 335   8  40 400  73 105 465 138 170 203 235 268 128 301
 333 193 366 398 258 431 463 496  28  61 421  94 126 486 159 191  51 224
 256 289 321 354 214 387 419 279 452 484 344  17  49  82 114 147   7 180
 212  72 245 277 137 310 342 375 408 440 300 473   5 365  38  70 430 103
 135 168 201 233  93 266 298 158 331 363 223 396 428 461 494  26 386  59
  91 451 124 156  16 189 221 254 287 319 179 352 384 244 417 449 309 482
  14  47 407  80 112 472 145 177  37 210 242 102 275 307 340 200 373 405
 265 438 470 330   3  35 395  68 100 133 493 166 198  58 231 263 123 296
 328 188 286 351 416 481  79 144 209 274 372 437   2  67 165 230 295 360
  65 458  23  88 153 358 251 316 381 446 151  44 109 174 444 337 402 467
 237 130 195 260  30 423 488  53 118 323 216 281 346 116   9  74 139 409
 302 367 432 202  95 160 225 495 388 453  18 288 181 246 311  81 474  39
 104 374 267 332 397 167  60 125 190 460 353 418 483 146 211 276 439   4
  69 232 297 362  25  90 155 253 318 383 448  46 111 176 241 339 404 469
 132 197 262 425 490  55 218 283 348 413  11 411 204 497 390 455  20  85
 290 183 248 313 378  83 476  41 106 171 376 478 150 443 236 269 334 399
 464 357  29  62 127 192 257 322 355 420 485  50 115 148 213 278 343 441
   6  71 136 169 234 299 364 429 462  27  92 157 222 255 320 385 450  15
  48 113 178 243 308 341 406 471  36 101 134 199 264 329 394 427 492  57
 122 187 220 285 350 415 480  13  78 143 208 273 306 185]
state ['WA' 'WI' 'KS' 'KY' 'ND' 'OK' 'AZ' 'CA' 'MI' 'MN' 'SC' 'TN' 'FL' 'HI'
 'NV' 'NH' 'VA' 'WV' 'IA' 'OH' 'AK' 'AR' 'MA' 'SD' 'DE' 'GA' 'NE' 'IN'
 'NC' 'MD' 'RI' 'MT' 'VT' 'CO' 'MO' 'UT' 'ID' 'NM' 'WY' 'LA' 'OR' 'MS'
 'TX' 'NJ' 'NY' 'AL' 'PA' 'CT' 'IL' 'ME']
totalminsusedinlastmonth [ 15 212 216 412 416 113 116 313 316  13  17 214 217 414 417 114 118 315
 318  18 215 219 419 119 320  16  20 220 420 117 121 321  21 218 222 422
 122 319 323 322  19  23 223 423 120 124 324  24 221 225 425 125 326  22
  26 226 426 123 127 327  27 224 228 428 128 325 329  29 229 429 126 130
 330  30 227 231 431 131 328 332  32 232 433 133 333  33 230 234 434 134
 331 335  35 235 432 436 136 336  37 233 237 437 137 334 338  38 238 435
 439 139 339  36  40 240 440 140 337 341  41 241 438 442 142 342  39  43
 243 443 144 340 344  44 244 441 445 145 345  42  46 246 446 143 147 347
  47 248 444 448 148 348  45  49 249 449 146 150 350  50 247 251 451 151
 351  48  52 252 452 149 153 353  53 250 254 454 154 355  51  55 255 455
 152 156 356  56 253 257 457 157 354 358  58 258 458 155 159 359  59 256
 260 460 160 357 361  61 261 462 158 162 362  62 259 263 463 163 360 364
  64 264 461 465 165 365  66 262 266 466 166 363 367  67 267 464 468 168
 368  65  69 269 469 169 366 370  70 270 467 471 171 371  68  72 272 472
 173 369 373  73 273 470 474 174 374  71  75 275 475 172 176 376  76 276
 473 477 177 377  74  78 278 478 175 179 379  79 280 476 480 180 380  77
  81 281 481 178 182 382  82 279 283 483 183 384  80  84 284 484 181 185
 385  85 282 286 486 186 383 387  87 287 487 184 188 388  88 285 289 489
 189 386 390  90 290 491 187 191 391  91 288 292 492 192 389 393  93 293
 490 494 194 394  94 291 295 495 195 392 396  96 296 493 497 197 397  98
 298 498 198 395 399  99 299 496   0 200 400  97 101 301   1 202 398 402
 102 302 499   3 203 403 100 104 304   4 201 205 405 105 305   2   6 206
 406 103 107 307   7 204 208 408 108 309   5   9 209 409 106 110 310  10
 207 211 411 111 308 312  12 109 210 311 213 314 415 317 418 421 424  25
 427  28 129  31 132  34 135 236 138 239 141 242 343 245 346 447 349 450
 352 453  54 456  57 459  60 161  63 164 265 167 268 170 271 372 274 375
 277 378 479 381 482  83 485  86 488  89 190  92 193 294  95 196 297 199
 300 401 303 404 306 407   8 410  11 112 413  14 115 430]
unpaidbalance [ 19  34 144 159 143 158  18  33  68 178 193  53  52  67 177 192 191  51
  66 176 175 190  50  65  64 174 189  49  48  63 173 188 187  47  62 172
 186  46  61 171 170 185  45  60  59 169 184  44  43  58 168 183 218  78
  93 203 202 217  77  92  91 201 216  76  75  90 200 215  74  89 199 214
 213  73  88 198 197 212  72  87  86 196 211  71  70  85 195 210 209  69
  84 194 208  83  82 207  81 206  80 205 204  79  98 113 223 238  97 112
 222 237 236  96 111 221 233 128 163  23 108  38   3 148  57 182  56 181
 160  20  35 145  55 180 179  54 104 229 103 228 227 102 232 247 107 122
 231 246 106 121 230 245 105 120 155  15  30 140 100 225 119  14  29 139
 154 244 118 243 242 117 116 226  11  95  10  25 240 135 220 115 150   9
  24 134 149 133   8   7  22 132 147 110 235   5 130 129   4 142   2  17
 127 126 141   1  16 125   0 157  32 156  31 136  99 224  28 153  27  42
 152 167   6  41 151 166 131  26 241  40 165 164  94 239  39 219 114 162
  37  21  36 146 161 124 234 249 109 123 248 138  13  12 137 101]
usesinternetservice ['No' 'Yes']
usesvoiceservice ['No' 'Yes']
percentagecalloutsidenetwork [0.82 0.27 0.48 0.94 0.15 0.61 0.28 0.49 0.16 0.95 0.83 0.81 0.02 0.69
 0.36 0.03 0.7  0.37 0.04 0.71 0.5  0.17 0.38 0.05 0.84 0.72 0.51 0.18
 0.39 0.06 0.85 0.73 0.52 0.4  0.19 0.86 0.07 0.74 0.53 0.41 0.2  0.87
 0.08 0.75 0.54 0.42 0.21 0.88 0.09 0.76 0.55 0.43 0.22 0.89 0.1  0.77
 0.56 0.44 0.23 0.11 0.9  0.57 0.78 0.45 0.24 0.12 0.91 0.58 0.79 0.46
 0.25 0.13 0.92 0.59 0.8  0.47 0.26 0.14 0.93 0.6  0.62 0.29 0.96 0.63
 0.3  0.97 0.64 0.31 0.98 0.65 0.32 0.99 0.66 0.33 0.   0.67 0.34 0.01
 0.68 0.35]
totalcallduration [5971 3981 7379 ... 3871 7651 7200]
avgcallduration [ 663  995  737 ...  207 1302 1249]
churn [0 1]
year [2015]
month [1 2 3]

##### Произведем кодирование категориальных переменных:

In [12]:
cat_columns = df.dtypes[df.dtypes == 'object'].index

for i in cat_columns:
    if i in ['customersuspended', 'homeowner', 'usesinternetservice', 'usesvoiceservice']:
        df[i] = df[i].map({'Yes':1, 'No':0})
    if i == 'education':
        df[i] = df[i].map({'High School or below':1,      
                            'Bachelor or equivalent':2,
                            'Master or equivalent':3,
                            'PhD or equivalent':4})
    if i == 'maritalstatus':
        df[i] = df[i].map({'Married':1, 'Single':0})
    if i == 'noadditionallines':
        df.drop('noadditionallines', axis = 1, inplace = True)
    if i == 'gender':
        df[i] = df[i].map({'Male':1, 'Female':0})

#####  Поскольку некоторые клиенты были у нас по 2 и 3 месяца, они стали отточными только в последний месяц.
##### Соответственно, необходимо изменить целевую переменную соответствующим образом:

In [13]:
for i in df[df['churn'] == 1]['customerid'].unique():
    df.loc[df[df['customerid'] == i][:-1].index, 'churn'] = 0

##### Поскольку клиенты с одинаковым ID отличаются только двумя параметрами (avgcallduration и totalcallduration), необходимо, чтобы в трейне и тесте содержались разные клиенты:

In [14]:
m = df.groupby('customerid')['month'].agg({'month':lambda x: x.max()})

df1 = df[df['customerid'].isin(m[m['month'] == 1].index)] # Только 1 месяц
df2 = df[df['customerid'].isin(m[m['month'] == 2].index)] # Только 1 и 2 месяц
df3 = df[df['customerid'].isin(m[m['month'] == 3].index)] # Все 3 месяца

df_tst = df2[df2['customerid'].isin(df2['customerid'].unique()[7160:])] # Разносим трейн и тест в соотношении 70%\30%
df_trn = df2.drop(df_tst.index)

train = pd.concat([df1, df_trn], axis = 0)
test = pd.concat([df3, df_tst], axis = 0)

C:\Users\mi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.

##### Добавим новый признак, который будет отображать разницу между минимальным и максимальным значением для предикторов 
##### 'avgcallduration' и 'totalcallduration':

In [15]:
k1 = train.groupby(['customerid']).agg({'avgcallduration': lambda x: x.max() - x.min(), 
                                      'totalcallduration': lambda x:x.max() - x.min(),
                                      'customerid':lambda x: x.min()})
k2 = test.groupby(['customerid']).agg({'avgcallduration': lambda x: x.max() - x.min(), 
                                      'totalcallduration': lambda x:x.max() - x.min(),
                                      'customerid':lambda x: x.min()})

train = train.merge(k1, left_on='customerid', right_on='customerid')
test = test.merge(k2, left_on='customerid', right_on='customerid')

#####  Для категориальных и некоторых дискретных переменных с малым количеством уникальных значений произведем кодирование
#####  частотами (frequency_encoding), а также средним значением целевой переменной (mean_target_encoding):

In [16]:
for i in ['occupation',                       
'state',                           
'numberofcomplaints',                                 
'numberofmonthunpaid',                             
'callfailurerate', 
'calldroprate', 'customersuspended', 'homeowner', 'education', 'maritalstatus', 'gender']:
    freq_encoding = train[i].value_counts() / len(train[i])
    train[i + 'freq'] = train[i].map(freq_encoding)
    test[i + 'freq'] = test[i].map(freq_encoding)
    
    train[i + ' mean'] = train[i].map(train.groupby(i)['churn'].mean())
    test[i + ' mean'] = test[i].map(train.groupby(i)['churn'].mean())

In [17]:
# Удаляем "бесполезные переменные":
train.drop(['customerid', 'year', 'state', 'occupation', 'callingnum'], axis = 1, inplace = True)
test.drop(['customerid', 'year', 'state', 'occupation', 'callingnum'], axis = 1, inplace = True)

In [18]:
y_train = train['churn']
train.drop('churn', axis=1, inplace = True)

y_test = test['churn']
test.drop('churn', axis=1, inplace = True)

In [19]:
from sklearn.preprocessing import StandardScaler
 
scaler = StandardScaler()

scaler.fit(train)

train_s = scaler.transform(train)
test_s = scaler.transform(test)

##### Построим модель логистической регресии (для этого, шагом ранее делалось масштабирование):

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

logreg_grid = LogisticRegression() 

param_grid = {'C': [0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 2], 'penalty' :['l1', 'l2']} # Задаем решетку гиперпараметров. 

stratcv = StratifiedKFold(n_splits=5) # Указываем количество блоков для кросс-валидации.

#создаем экземпляр класса GridSearchCV
grid_search = GridSearchCV(logreg_grid, param_grid, 
                           scoring='roc_auc', 
                           n_jobs=-1, cv=stratcv)

grid_search.fit(train_s, y_train)

test_score = roc_auc_score(y_test, grid_search.predict_proba(test_s)[:, 1])
#смотрим результаты GridSearchCV
print('AUC на тестовой выборке: {:.3f}'.format(test_score))
print('Наилучшее значение гиперпараметров: {}'.format(grid_search.best_params_))
print('Наилучшее значение AUC: {:.3f}'.format(grid_search.best_score_))

AUC на тестовой выборке: 0.818
Наилучшее значение гиперпараметров: {'C': 0.05, 'penalty': 'l1'}
Наилучшее значение AUC: 0.839

#### Итак, мы получили следующие показатели:
##### AUC_ROC - 0.818

##### Некоторые примечания по оценке качества модели:
##### 1. Кросс-валидация была сделана не совсем корректно - для каждого фолда необходимо было выполнять отдельное кодирование частотами и mean_target. Поэтому реалистичная оценка качества модели будет несколько ниже, хоть и не намного.
##### 2. Также, можно попробовать включить в трейн более ранние месяцы (1 и часть 2), а в тест - более поздние (3 и оставшаяся часть 2)

### Оценка полученных результатов

##### Для оценки результатов необходимо перейти от клиентов к деньгам. Потенциальную прибыль от каждого клиента мы можем посчитать как количество минут (totalcallduration). 
##### Данное предположение конечно же довольно наивно, поскольку мы не учитываем стоимость минут клиента (тариф), размер скидки для удержания и другие факторы.

In [21]:
Evaluate_results = pd.concat([y_test, pd.Series(grid_search.predict(test_s)), test], axis = 1)

In [22]:
# Сначала определим True Positive – случаи, когда модель предсказала отток верно:
TP = Evaluate_results[(Evaluate_results['churn'] == 1) & (Evaluate_results[Evaluate_results.columns[1]] == 1)]

In [23]:
print('Количество минут, потенциально потраченных абонентом, которого "ПОПЫТАЛИСЬ" удержать  -  ', TP['totalcallduration_x'].sum())

Количество минут, потенциально потраченных абонентом, которого "ПОПЫТАЛИСЬ" удержать  -   122140

In [24]:
print('Процент минут отточных абонентов, \
которых удалось удержать к общему числу минут отточных абонентов   -  ', \
      round(TP['totalcallduration_x'].sum()/Evaluate_results[(Evaluate_results['churn'] == 1)]['totalcallduration_x'].sum(), 3), '%')

Процент минут отточных абонентов, которых удалось удержать к общему числу минут отточных абонентов   -   0.304 %

In [25]:
FN = Evaluate_results[(Evaluate_results['churn'] == 1) & (Evaluate_results[Evaluate_results.columns[1]] == 0)]

In [26]:
print('Количество минут, потенциально потраченных абонентом, которого "НЕ ПОПЫТАЛИСЬ" удержать  -  ', FN['totalcallduration_x'].sum())

Количество минут, потенциально потраченных абонентом, которого "НЕ ПОПЫТАЛИСЬ" удержать  -   279617

In [27]:
FP = Evaluate_results[(Evaluate_results['churn'] == 0) & (Evaluate_results[Evaluate_results.columns[1]] == 1)]

In [28]:
print('Количество минут, потенциально потраченных абонентом, которого не нужно было бы удерживать  -  ', FP['totalcallduration_x'].sum())

Количество минут, потенциально потраченных абонентом, которого не нужно было бы удерживать  -   1015847

#### Заключение:

##### Обученная модель выдает верный прогноз для отточных абонентов, которые используют около 30% всех минут оттоковых абонентов. Данных клиентов можно попробовать удержать с помощью предоставления бесплатных минут или перевода на более выгодный тариф.
##### В целях экономии бюджета, выделенного на удержание клиентов, можно не давать или давать минимальные скидки клиентам, чей скор остаться был относительно не высоким. Это можно сделать с помощью оптимального подбора threshold.

##### Также мы можем увидеть, что модель не определяет довольно большой процент оттоковых клиентов, что говорит о её несовершенстве. Возможно, обогащение данными (особенно примерами с положительным классом целевой переменной) поможет улучшить качество модели.